### ISSUE TITLE
Can not add plugin 

### ISSUE THREAD

**Issue by Fibinacci** [akofman/cordova-plugin-disable-bitcode#5]
When I try plugin add project ;

Error: Cannot find module 'xcode'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/testuser/desktop/Projects/TestPlugin2/plugins/cordova-plugin-disable-bitcode/src/disable-bitcode.js:7:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

show this error. And plugin wasn't add.

**Comment by akofman** [comment]
Hello @Fibinacci,

I forgot to mention it in the installation section but you have to add the dependency to xcode in your project : `npm i -D xcode`.

**Comment by Fibinacci** [comment]
Yes, I can do it this way with terminal . But how can I do a project I created with Visual Studio .

**Comment by akofman** [comment]
I'm not an expert of VisualStudio but it seems you just have to add this
dependency (xcode) in the package.json file of your project then save.
VisualStudio will automatically download and install it as soon as you save.

Hope that helps.
Le 14 janv. 2016 8:31 AM, "Üsame Kaldırım" notifications@github.com a
écrit :
